/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicLoginSuccessRouteImport } from './routes/_public/login-success'
import { Route as PublicLoginFailureRouteImport } from './routes/_public/login-failure'
import { Route as AuthRecordRouteImport } from './routes/_auth/record'
import { Route as PublicWelcomeIndexRouteImport } from './routes/_public/welcome/index'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as AuthRecordIndexRouteImport } from './routes/_auth/record/index'
import { Route as AuthMyIndexRouteImport } from './routes/_auth/my/index'
import { Route as AuthRecordUploadRouteImport } from './routes/_auth/record/upload'
import { Route as AuthRecordThumbnailRouteImport } from './routes/_auth/record/thumbnail'
import { Route as AuthRecordStudioRouteImport } from './routes/_auth/record/studio'
import { Route as AuthRecordPreviewRouteImport } from './routes/_auth/record/preview'
import { Route as AuthRecordPermissionRouteImport } from './routes/_auth/record/permission'
import { Route as AuthVideoDateIndexRouteImport } from './routes/_auth/video/$date/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginSuccessRoute = PublicLoginSuccessRouteImport.update({
  id: '/login-success',
  path: '/login-success',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginFailureRoute = PublicLoginFailureRouteImport.update({
  id: '/login-failure',
  path: '/login-failure',
  getParentRoute: () => PublicRoute,
} as any)
const AuthRecordRoute = AuthRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AuthRoute,
} as any)
const PublicWelcomeIndexRoute = PublicWelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthRecordIndexRoute = AuthRecordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRecordRoute,
} as any)
const AuthMyIndexRoute = AuthMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecordUploadRoute = AuthRecordUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthRecordRoute,
} as any)
const AuthRecordThumbnailRoute = AuthRecordThumbnailRouteImport.update({
  id: '/thumbnail',
  path: '/thumbnail',
  getParentRoute: () => AuthRecordRoute,
} as any)
const AuthRecordStudioRoute = AuthRecordStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthRecordRoute,
} as any)
const AuthRecordPreviewRoute = AuthRecordPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AuthRecordRoute,
} as any)
const AuthRecordPermissionRoute = AuthRecordPermissionRouteImport.update({
  id: '/permission',
  path: '/permission',
  getParentRoute: () => AuthRecordRoute,
} as any)
const AuthVideoDateIndexRoute = AuthVideoDateIndexRouteImport.update({
  id: '/video/$date/',
  path: '/video/$date/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/record': typeof AuthRecordRouteWithChildren
  '/login-failure': typeof PublicLoginFailureRoute
  '/login-success': typeof PublicLoginSuccessRoute
  '/record/permission': typeof AuthRecordPermissionRoute
  '/record/preview': typeof AuthRecordPreviewRoute
  '/record/studio': typeof AuthRecordStudioRoute
  '/record/thumbnail': typeof AuthRecordThumbnailRoute
  '/record/upload': typeof AuthRecordUploadRoute
  '/my': typeof AuthMyIndexRoute
  '/record/': typeof AuthRecordIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/welcome': typeof PublicWelcomeIndexRoute
  '/video/$date': typeof AuthVideoDateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login-failure': typeof PublicLoginFailureRoute
  '/login-success': typeof PublicLoginSuccessRoute
  '/record/permission': typeof AuthRecordPermissionRoute
  '/record/preview': typeof AuthRecordPreviewRoute
  '/record/studio': typeof AuthRecordStudioRoute
  '/record/thumbnail': typeof AuthRecordThumbnailRoute
  '/record/upload': typeof AuthRecordUploadRoute
  '/my': typeof AuthMyIndexRoute
  '/record': typeof AuthRecordIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/welcome': typeof PublicWelcomeIndexRoute
  '/video/$date': typeof AuthVideoDateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/record': typeof AuthRecordRouteWithChildren
  '/_public/login-failure': typeof PublicLoginFailureRoute
  '/_public/login-success': typeof PublicLoginSuccessRoute
  '/_auth/record/permission': typeof AuthRecordPermissionRoute
  '/_auth/record/preview': typeof AuthRecordPreviewRoute
  '/_auth/record/studio': typeof AuthRecordStudioRoute
  '/_auth/record/thumbnail': typeof AuthRecordThumbnailRoute
  '/_auth/record/upload': typeof AuthRecordUploadRoute
  '/_auth/my/': typeof AuthMyIndexRoute
  '/_auth/record/': typeof AuthRecordIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_public/welcome/': typeof PublicWelcomeIndexRoute
  '/_auth/video/$date/': typeof AuthVideoDateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/record'
    | '/login-failure'
    | '/login-success'
    | '/record/permission'
    | '/record/preview'
    | '/record/studio'
    | '/record/thumbnail'
    | '/record/upload'
    | '/my'
    | '/record/'
    | '/login'
    | '/welcome'
    | '/video/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login-failure'
    | '/login-success'
    | '/record/permission'
    | '/record/preview'
    | '/record/studio'
    | '/record/thumbnail'
    | '/record/upload'
    | '/my'
    | '/record'
    | '/login'
    | '/welcome'
    | '/video/$date'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/_auth/record'
    | '/_public/login-failure'
    | '/_public/login-success'
    | '/_auth/record/permission'
    | '/_auth/record/preview'
    | '/_auth/record/studio'
    | '/_auth/record/thumbnail'
    | '/_auth/record/upload'
    | '/_auth/my/'
    | '/_auth/record/'
    | '/_public/login/'
    | '/_public/welcome/'
    | '/_auth/video/$date/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login-success': {
      id: '/_public/login-success'
      path: '/login-success'
      fullPath: '/login-success'
      preLoaderRoute: typeof PublicLoginSuccessRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login-failure': {
      id: '/_public/login-failure'
      path: '/login-failure'
      fullPath: '/login-failure'
      preLoaderRoute: typeof PublicLoginFailureRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/record': {
      id: '/_auth/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AuthRecordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/welcome/': {
      id: '/_public/welcome/'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof PublicWelcomeIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/record/': {
      id: '/_auth/record/'
      path: '/'
      fullPath: '/record/'
      preLoaderRoute: typeof AuthRecordIndexRouteImport
      parentRoute: typeof AuthRecordRoute
    }
    '/_auth/my/': {
      id: '/_auth/my/'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthMyIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/record/upload': {
      id: '/_auth/record/upload'
      path: '/upload'
      fullPath: '/record/upload'
      preLoaderRoute: typeof AuthRecordUploadRouteImport
      parentRoute: typeof AuthRecordRoute
    }
    '/_auth/record/thumbnail': {
      id: '/_auth/record/thumbnail'
      path: '/thumbnail'
      fullPath: '/record/thumbnail'
      preLoaderRoute: typeof AuthRecordThumbnailRouteImport
      parentRoute: typeof AuthRecordRoute
    }
    '/_auth/record/studio': {
      id: '/_auth/record/studio'
      path: '/studio'
      fullPath: '/record/studio'
      preLoaderRoute: typeof AuthRecordStudioRouteImport
      parentRoute: typeof AuthRecordRoute
    }
    '/_auth/record/preview': {
      id: '/_auth/record/preview'
      path: '/preview'
      fullPath: '/record/preview'
      preLoaderRoute: typeof AuthRecordPreviewRouteImport
      parentRoute: typeof AuthRecordRoute
    }
    '/_auth/record/permission': {
      id: '/_auth/record/permission'
      path: '/permission'
      fullPath: '/record/permission'
      preLoaderRoute: typeof AuthRecordPermissionRouteImport
      parentRoute: typeof AuthRecordRoute
    }
    '/_auth/video/$date/': {
      id: '/_auth/video/$date/'
      path: '/video/$date'
      fullPath: '/video/$date'
      preLoaderRoute: typeof AuthVideoDateIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRecordRouteChildren {
  AuthRecordPermissionRoute: typeof AuthRecordPermissionRoute
  AuthRecordPreviewRoute: typeof AuthRecordPreviewRoute
  AuthRecordStudioRoute: typeof AuthRecordStudioRoute
  AuthRecordThumbnailRoute: typeof AuthRecordThumbnailRoute
  AuthRecordUploadRoute: typeof AuthRecordUploadRoute
  AuthRecordIndexRoute: typeof AuthRecordIndexRoute
}

const AuthRecordRouteChildren: AuthRecordRouteChildren = {
  AuthRecordPermissionRoute: AuthRecordPermissionRoute,
  AuthRecordPreviewRoute: AuthRecordPreviewRoute,
  AuthRecordStudioRoute: AuthRecordStudioRoute,
  AuthRecordThumbnailRoute: AuthRecordThumbnailRoute,
  AuthRecordUploadRoute: AuthRecordUploadRoute,
  AuthRecordIndexRoute: AuthRecordIndexRoute,
}

const AuthRecordRouteWithChildren = AuthRecordRoute._addFileChildren(
  AuthRecordRouteChildren,
)

interface AuthRouteChildren {
  AuthRecordRoute: typeof AuthRecordRouteWithChildren
  AuthMyIndexRoute: typeof AuthMyIndexRoute
  AuthVideoDateIndexRoute: typeof AuthVideoDateIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRecordRoute: AuthRecordRouteWithChildren,
  AuthMyIndexRoute: AuthMyIndexRoute,
  AuthVideoDateIndexRoute: AuthVideoDateIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginFailureRoute: typeof PublicLoginFailureRoute
  PublicLoginSuccessRoute: typeof PublicLoginSuccessRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
  PublicWelcomeIndexRoute: typeof PublicWelcomeIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginFailureRoute: PublicLoginFailureRoute,
  PublicLoginSuccessRoute: PublicLoginSuccessRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
  PublicWelcomeIndexRoute: PublicWelcomeIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
